name: video_player_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.6.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: 9.2.0
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.1.14
  video_compress: ^3.1.2
  video_player: ^2.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: 'assets/images/logo.png'
  background_image: 'assets/images/bg_image.jpeg'

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/title2.png
    - assets/images/logo_full.png
    - assets/images/bg_image.jpeg
    - assets/lottie/loading.json
    - assets/images/recently.png
    - assets/images/mostly.png
    - assets/images/favourites.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
