name: video_player_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_info_plus: ^9.0.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: 10.1.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.1
  video_compress: ^3.1.2
  video_player: ^2.7.1

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: 'assets/images/logo.png'
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/title2.png
    - assets/images/logo_full.png
    - assets/images/bg.png
    - assets/images/thumbnail_placeholder.jpg
  fonts:
    - family: ChelseaMarket
      fonts:
        - asset: assets/fonts/ChelseaMarket-Regular.ttf
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf
    - family: Koulen
      fonts:
        - asset: assets/fonts/Koulen-Regular.ttf
    - family: NixieOne
      fonts:
        - asset: assets/fonts/NixieOne-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
